#ifndef MAIN_H_
#define MAIN_H_


typedef enum {WAIT, RFID_EVENT, RAND_GEN_EVENT, DISPLAY_EVENT, ADC_EVENT, BUTTON_EVENT} RFIDICEBOARDSTATE_T;

extern RFIDICEBOARDSTATE_T RFIDiceBoardState;


#endif MAIN_H
